### ISSUE TITLE
Running on TestNet

### ISSUE THREAD

**Issue by ghost** [dgarage/NBXplorer#1]
Hi,

testnet works with nbitcoin @127.0.0.1:18333 with bitcoin core without a problem!

but here i get an exception: server couldn't be connected
**@ 
var isValid = ((JObject)rpcClient.SendCommand("validateaddress", address.ToString()).Result)["isvalid"].Value<bool>();**

info: Configuration:  Using APPDATA environment variable for initializing application data
info: Configuration:  Configuration file set to C:\Users\mm\AppData\Roaming\NBXplorer\TestNet\settings.config
info: Configuration:  Network: TestNet
info: Configuration:  Data directory set to C:\Users\mm\AppData\Roaming\NBXplorer\TestNet
info: Configuration:  Configuration file set to C:\Users\mm\AppData\Roaming\NBXplorer\TestNet\settings.config
info: Configuration:  Testing RPC connection to http://localhost:18332/
fail: Configuration:  Error connecting to RPC server An error occurred while sending the request. Die Serververbindung konnte nicht hergestellt werden
fail: Configuration:  NBXplorer.Configuration.ConfigException
         at NBXplorer.Configuration.RPCArgs.ConfigureRPCClient(Network network) in C:\Cracktros\Amiga\NBXplorer-master\NBXplorer\Configuration\RPCArgs.cs:line 98
         at NBXplorer.ExplorerRuntime..ctor(ExplorerConfiguration configuration) in C:\Cracktros\Amiga\NBXplorer-master\NBXplorer\ExplorerRuntime.cs:line 32
         at NBXplorer.Configuration.ExplorerConfiguration.CreateRuntime() in C:\Cracktros\Amiga\NBXplorer-master\NBXplorer\Configuration\ExplorerConfiguration.cs:line 147

         at NBXplorer.Extensions.<>c.<UseNBXplorer>b__0_1(IServiceProvider o) in C:\Cracktros\Amiga\NBXplorer-master\NBXplorer\Extensions.cs:line 25
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
         at NBXplorer.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IServiceProvider serviceProvider) in C:\Cracktros\
Amiga\NBXplorer-master\NBXplorer\Startup.cs:line 68

config file:

```
####Common Commands####
####If Bitcoin Core is running with default settings, you should not need to modify this file####
####All those options can be passed by through command like arguments (ie `-port=19382`)####
## This is the RPC Connection to your node
rpc.url=http://localhost:18332/
rpc.user=
rpc.password=
rpc.cookiefile=C:\Users\mm\Documents\Bitcoin\.cookie

## This is the connection to your node through P2P
node.endpoint=127.0.0.1:18444

## startheight defines from which block you will start scanning, if -1 is set, it will use current blockchain height
#startheight=-1
## rescan forces a rescan from startheight
#rescan=0


####Server Commands####
#port=24444
#bind=127.0.0.1
#testnet=0
#regtest=0
```

**Comment by NicolasDorier** [comment]
Sorry for late reply, can you try again.
Also run with `dotnet run -testnet`

**Comment by NicolasDorier** [comment]
Closing due to inactivity, let me know if you can;t get it to work on testnet. I am using it in 'prod' on testnet right now without issue.
