### ISSUE TITLE
Error when calling GetFeeRateAsync on BCH node

### ISSUE THREAD

**Issue by chriswhellams** [dgarage/NBXplorer#115]
When I use the client library to Get BCH mining fees NBXplorer throws an error. I have a connection to my BCH node from NBXplorer, it is initialising ok and parsing blocks ok  

Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLHEKSUNPITU", Request id "0HLHEKSUNPITU:00000002": An unhandled exception was thrown by the application.
NBitcoin.RPC.RPCException: Method not found
at NBitcoin.RPC.RPCResponse.ThrowIfError()
   at NBitcoin.RPC.RPCClient.SendCommandAsyncCore(RPCRequest request, Boolean throwIfRPCError)
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, Boolean throwIfRPCError)
   at NBXplorer.Controllers.MainController.GetFeeRate(Int32 blockCount, String cryptoCode) in C:\Users\chris\source\repos\NBXplorer\NBXplorer\Controllers\MainController.cs:line 81

**Comment by NicolasDorier** [comment]
Can you check what we can use for getting the fees on BCH?

**Comment by chriswhellams** [comment]
> Can you check what we can use for getting the fees on BCH?

arghh ..I was dreading that you would say that ! Yes, I'm on vacation next week so I will try and take a look . The BCH team are just so great.... :/
