### ISSUE TITLE
Random timeouts: TaskCanceledException

### ISSUE THREAD

**Issue by MyNameIsOka** [dgarage/NBXplorer#254]
Hi everybody,

since some time I am getting random timeouts when calling NBXplorer multiple times in a short time, when running Jest tests. The errors are occurring really inconsistently, though.
Checking the logs, I get this error:
```
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLV1RNGKADF7", Request id "0HLV1RNGKADF7:00000001": An unhandled exception was thrown by the application.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

Do you happen to know why this error might occur? 
When running the tests, NBXplorer is called ~10 times in a time frame of 20 seconds.

I am on NBXplorer version 2.1.23

Thank you for any insight you can give me!

Here is more of the log: 
```
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/RegTest/settings.config
info: Configuration:  Network: Regtest
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Regtest
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Testing RPC connection to http://bitcoind:18443/
info: Configuration:  BTC: RPC connection successful
Hosting environment: Production
Content root path: /app/
Now listening on: http://0.0.0.0:32838
Application started. Press Ctrl+C to shut down.
info: Configuration:  BTC: Full node version detected: 170000
info: Configuration:  BTC: Loading chain from cache...
info: Configuration:  BTC: Height: 417117
info: Configuration:  BTC: Trying to connect via the P2P protocol to trusted node (bitcoind:39388)...
info: Explorer:       BTC: TCP Connection succeed, handshaking...
info: Explorer:       BTC: Handshaked
info: Configuration:  BTC: Loading chain from node
info: Explorer:       BTC: Loading chain...
info: Explorer:       BTC: Chain loaded
info: Explorer:       BTC: NBXplorer is correctly whitelisted by the node
info: Configuration:  BTC: Height: 417123
info: Configuration:  BTC: Saving chain to cache...
info: Configuration:  BTC: Chain cached
info: Explorer:       BTC: Starting scan at block 417113
info: Events:         BTC: Node state changed: NotStarted => NBXplorerSynching
info: Events:         BTC: Node state changed: NBXplorerSynching => Ready
info: Events:         BTC: New block 279bbc3e402b2661fce0eb80216e36024a828b2e809c744a6cb92d29e4882897 (417116)
info: Events:         BTC: New block 665693e39a23bdfe164988d0b3443f217662b3010e81ac47272419ba6d65fef8 (417114)
info: Events:         BTC: New block 24699bb535438f9027a439ab2e60f68c0b9eb2ae142a420a831685d38422efe0 (417115)
info: Events:         BTC: New block 48c5573c717c2c7dcbf479cce3deef0871393e0fc557eda97bb52480b931970a (417117)
info: Events:         BTC: New block 25fd772dc9e444e85b9466859481edd73793e01c39209b21909389e51c6337e6 (417118)
info: Events:         BTC: New block 273ec06fceafa6f534265d65ba926fe53a5a3894b812b93a60aa5b61ccf8ea36 (417119)
info: Events:         BTC: New block 15807a94b182568129fe92a9f431b4d5b5db751dbf18e2826d7a7c9989f32bf6 (417120)
info: Events:         BTC: New block 3724f2e19f66965c129f1195d3e892c7bf56e523f914841840574f3793825ae5 (417121)
info: Events:         BTC: New block 5906de23a281d6e1c5f4e4f73cfa7f4794a58ddaa79281828cf63ce3136cffa2 (417122)
info: Events:         BTC: New block 1be3473a03bacd730b328acd02d32aef4df2078f0f9c6d3cd585a848c217d38c (417123)
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLV1RNGKADF7", Request id "0HLV1RNGKADF7:00000001": An unhandled exception was thrown by the application.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.CheckHealthAsync(Func`2 predicate, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Events:         BTC: New block 0a28d2037f48dd557f35f94c328379f5fa19c72e11ca8d3fec5095319325569c (417124)
info: Events:         BTC: New block 75bceb61d703b702d8c2e5f0c2aba41726acf5576a5afda63f7376f8bb24b52e (417125)
info: Events:         BTC: New block 3889537175d002e8eee2f6edd92518f715eccf140617b43cef55ad169dee4c07 (417126)
info: Events:         BTC: New block 6ecc582690ddc5190b34705f7b01013d434e4aebdad6c9410cd0735402eab121 (417127)
info: Events:         BTC: New block 557446d2fed586dff430a81d04e79c6156e4510237f1ac6a0ec682b4db3830be (417128)
...
...
...
info: Events:         BTC: New block 3a1b10106316a213b75028eea8e0432dc217348c2668dba053ed38841bb3ea5c (417142)
info: Events:         BTC: New block 0af2679cb362e41d303fe6dea2d0491390b2e21f08ba357b09ceb594c5c6d5d9 (417143)
info: Events:         BTC: New block 12d1543295bfc69fc62c3fa9786827bcd9513f0d74da4fee0c2ea58249e8b0e1 (417144)
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLV1RNGKAEA5", Request id "0HLV1RNGKAEA5:00000001": An unhandled exception was thrown by the application.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at NBXplorer.DBriizeTransactionContext.DoAsyncCore[T](Func`2 action, CancellationToken cancellation) in /source/NBXplorer/DBriizeTransactionContext.cs:line 134
   at NBXplorer.Repository.GetTransactions(TrackedSource trackedSource, uint256 txId, CancellationToken cancellation) in /source/NBXplorer/Repository.cs:line 749
   at NBXplorer.Controllers.MainController.GetAnnotatedTransactions(Repository repo, SlimChain chain, TrackedSource trackedSource, uint256 txId) in /source/NBXplorer/Controllers/MainController.cs:line 937
   at NBXplorer.Controllers.MainController.GetUTXOs(String cryptoCode, DerivationStrategyBase derivationScheme, BitcoinAddress address) in /source/NBXplorer/Controllers/MainController.cs:line 883
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLV1RNGKAEA3", Request id "0HLV1RNGKAEA3:00000001": An unhandled exception was thrown by the application.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at NBXplorer.DBriizeTransactionContext.DoAsyncCore[T](Func`2 action, CancellationToken cancellation) in /source/NBXplorer/DBriizeTransactionContext.cs:line 134
   at NBXplorer.Repository.GetTransactions(TrackedSource trackedSource, uint256 txId, CancellationToken cancellation) in /source/NBXplorer/Repository.cs:line 749
   at NBXplorer.Controllers.MainController.GetAnnotatedTransactions(Repository repo, SlimChain chain, TrackedSource trackedSource, uint256 txId) in /source/NBXplorer/Controllers/MainController.cs:line 937
   at NBXplorer.Controllers.MainController.GetUTXOs(String cryptoCode, DerivationStrategyBase derivationScheme, BitcoinAddress address) in /source/NBXplorer/Controllers/MainController.cs:line 883
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Events:         BTC: New block 66f19030c262c3e27b5c9b9463d0d7b8cdba441e27fe8b92c062d11c0e1291b6 (417145)
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLV1RNGKAEDM", Request id "0HLV1RNGKAEDM:00000001": An unhandled exception was thrown by the application.
...
[same error few more times]
...
info: Events:         BTC: New block 2402817cfcaa20a55c36008ead283e07362eb0eae0209d93a1826b16e4d874d8 (417146)
info: Events:         BTC: New block 6ab26be5a8009b2f1d610e3a16819ffebcc0f553138458084f131d3667729b8f (417147)

```

**Comment by NicolasDorier** [comment]
Never saw that happening. For the tests I recently (this week) added a commit which should make tests more reliable, but I don't see how this would be related to the errors you are seeing. Which OS?

**Comment by MyNameIsOka** [comment]
Hi Nicolas,

thank you for your response. 
After a lot of looking at the wrong places the reason seems to have been AWS in the end...
2 GB left disk space isn't enough for EC2 instances apparently.

Sorry for bothering.
