### ISSUE TITLE
Use '_TxContext?.DoAsync' replace '_TxContext.DoAsync' when _TxContext automatically disposed by DI container.

### ISSUE THREAD

**Issue by shiayoung** [dgarage/NBXplorer#261]
When scan blocks, if ctrl+c send to program, the following exception will be throwed:

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'DBriizeTransactionContext'.
   at NBXplorer.DBriizeTransactionContext.DoAsync(Action`1 action, CancellationToken cancellation) in E:\Projects\NBXplorer\DBriizeTransactionContext.cs:line 114
   at NBXplorer.Repository.SetIndexProgress(BlockLocator locator) in E:\Projects\NBXplorer\Repository.cs:line 363
   at NBXplorer.ExplorerBehavior.SaveMatches(Block block) in E:\Projects\NBXplorer\ExplorerBehavior.cs:line 333
   at NBXplorer.ExplorerBehavior.<>c__DisplayClass38_0.<<Run>b__0>d.MoveNext() in E:\Projects\NBXplorer\ExplorerBehavior.cs:line 269

**Comment by NicolasDorier** [comment]
@shiayoung can you test one master if that solve it?

**Comment by farukterzioglu** [comment]
I am also having the same issue. 

One different usage on me is that, NBX stay behind around one day, and trying to keep up without success.

One possible related issue, right now same blocks is being catched again and again. 
last ~100 blocks is always coming again. NBX can't be ready.
