### ISSUE TITLE
Getting error with every Dash block: "Error while calling event handler"

### ISSUE THREAD

**Issue by farukterzioglu** [dgarage/NBXplorer#271]
With every Dash block, NBX logs an error as;

```
info: Events:         DASH: New block 000000000000000445737adac55e7dda6faf1b5116dfe70b00f42013fcf9a31c (1290548)
fail: Events:         Error while calling event handler
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at NBXplorer.Analytics.FingerprintDistribution.CalculateFingerprint(Transaction tx) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 176
   at NBXplorer.Analytics.FingerprintDistribution..ctor(Block block) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 86
   at NBXplorer.Analytics.FingerprintDistribution.Calculate(Block block) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 16
   at NBXplorer.Analytics.FingerprintHostedService.<StartAsync>b__6_0(RawBlockEvent evt) in /NBXplorer/NBXplorer/Analytics/FingerprintHostedService.cs:line 62
   at NBXplorer.EventAggregator.Publish[T](T evt, Boolean internalEvent) in /NBXplorer/NBXplorer/EventAggregator.cs:line 104
```

Setup details;
One NBX instance is running for btc/ltc/dash. 
SavePrivateKey is false for all of them. Following multisig strategies.
RabbitMq publishing is active. 
Running from source code on Linux with commit: [8715d3d1ba2a519bd67678ed4be050487f2c9994](https://github.com/dgarage/NBXplorer/commit/8715d3d1ba2a519bd67678ed4be050487f2c9994)

**Comment by NicolasDorier** [comment]
thanks I need to fix this.

**Comment by NicolasDorier** [comment]
Please reopen if you see error again, making new version.

**Comment by farukterzioglu** [comment]
Still getting this exception sometimes. I have the latest commit.
Getting only on some Dash blocks. 
 
```
info: Events:         DASH: New block 0000000000000003adfd9ef8b5b6823c42620ed246b77b50a498240125260f84 (1304074)
fail: Events:         Error while calling event handler
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at NBXplorer.Analytics.FingerprintDistribution.CalculateFingerprint(Transaction tx) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 176
   at NBXplorer.Analytics.FingerprintDistribution..ctor(Block block) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 86
   at NBXplorer.Analytics.FingerprintDistribution.Calculate(Block block) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 16
   at NBXplorer.Analytics.FingerprintHostedService.<StartAsync>b__7_0(RawBlockEvent evt) in /NBXplorer/NBXplorer/Analytics/FingerprintHostedService.cs:line 63
   at NBXplorer.EventAggregator.Publish[T](T evt, Boolean internalEvent) in /NBXplorer/NBXplorer/EventAggregator.cs:line 104
info: Events:         DASH: New block 000000000000000032645b847e8583f1112a380f8c0a6cad174bd1b7ca001660 (1304075)
fail: Events:         Error while calling event handler
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at NBXplorer.Analytics.FingerprintDistribution.CalculateFingerprint(Transaction tx) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 176
   at NBXplorer.Analytics.FingerprintDistribution..ctor(Block block) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 86
   at NBXplorer.Analytics.FingerprintDistribution.Calculate(Block block) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 16
   at NBXplorer.Analytics.FingerprintHostedService.<StartAsync>b__7_0(RawBlockEvent evt) in /NBXplorer/NBXplorer/Analytics/FingerprintHostedService.cs:line 63
   at NBXplorer.EventAggregator.Publish[T](T evt, Boolean internalEvent) in /NBXplorer/NBXplorer/EventAggregator.cs:line 104
info: Events:         DASH: New block 0000000000000001471d3da198b31290968515acbb59aef9256e6f881e825049 (1304076)
```
