### ISSUE TITLE
NewTransaction events with confirmation < 0

### ISSUE THREAD

**Issue by farukterzioglu** [dgarage/NBXplorer#284]
While getting new transaction events (from RabbitMQ), sometimes (often recently) it sends messages with confirmation value below zero (e.g. -319303) and when I try to deserialize it, it throw `OverflowException` because `Confirmation` field is uint. 

Exception I got;

`
{   "Message": "Newtonsoft.Json.JsonSerializationException: Error setting value to Confirmations on NBXplorer.Models.TransactionResult.\n ---\u003e System.OverflowException: Arithmetic operation resulted in an overflow.\n   at lambda_method(Closure , Object , Object )\n   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)\n   --- End of inner exception stack trace ---\n   at Newtonsoft.Jso...
`

Event I got (attention to : **"confirmations":-319303**);

`{\"blockId\":\"000000000000000000051f4be9f653c457d7b40b991ed42ad371c072a0c10215\",\"trackedSource\":\"DERIVATIONSCHEME:2-of-xpub...-[p2sh]\",\"derivationStrategy\":\"2-of-xpub...-[p2sh]\",\"transactionData\":{\"confirmations\":-319303,\"blockId\":\"000000000000000000051f4be9f653c457d7b40b991ed42ad371c072a0c10215\",\"transactionHash\":\"...\",\"transaction\":\"...\",\"height\":639079,\"timestamp\":1594643768},\"outputs\":[{\"keyPath\":\"0/85374\",\"scriptPubKey\":\"...\",\"index\":0,\"value\":...}],\"cryptoCode\":\"BTC\"}",`

**Comment by NicolasDorier** [comment]
how can it overflow? If it got confirmed, the confirmations should not be less than 0. Checking.

**Comment by NicolasDorier** [comment]
@farukterzioglu I don't understand why the confirmation can be negative with our code. The other values are correct?

**Comment by NicolasDorier** [comment]
If you check the latest events via the endpoint on NBXPLorer, do you have the same negative confirmation?

Also this value is not even `-1` as a int.

**Comment by NicolasDorier** [comment]
```
{ "Message": "Newtonsoft.Json.JsonSerializationException: Error setting value to Confirmations on NBXplorer.Models.TransactionResult.\n ---\u003e System.OverflowException: Arithmetic operation resulted in an overflow.\n at lambda_method(Closure , Object , Object )\n at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)\n --- End of inner exception stack trace ---\n at Newtonsoft.Jso...
```

Do you have better stacktrace with lines? I don't see where this can be thrown.

**Comment by farukterzioglu** [comment]
Exception thrown in my code, while I try to deserialize the message. Full stack trace is at below. 
Messages before this one or after this one was totally ok, and once I got this kind of messages (with confirmation below 0) multiple in o row, needed to remove 3 messages from queue to process others. 

This happened multiple times, so I needed to handle this exception on my code for future occurrences. 

Let me check latest events with endpoint, if they are still below 0.

```
Newtonsoft.Json.JsonSerializationException: Error setting value to 'Confirmations' on 'NBXplorer.Models.TransactionResult'.
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at lambda_method(Closure , Object , Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Wallet.TransactionListener.Services.NBX.NbxListener.ProcessTxMessage(BasicDeliverEventArgs args, CancellationToken token) 
```

**Comment by NicolasDorier** [comment]
> Let me check latest events with endpoint, if they are still below 0.

Any update?

**Comment by farukterzioglu** [comment]
I was getting the exception while trying to parse `NewTransactionEvent`. Instead of that, when I get an exception I would try to parse ot its base class `NewEventBase`

but when I check it, it is as;
```
...
[JsonIgnore]
public long EventId { get; set; }
```
and for this reason I don't get EventId with RabbitMq messages.

I will try to guess the eventId and get the event details as soon as I got this exception, but didn't get it for a while. 

Any possibility to remove `[JsonIgnore]` from EventId, so I can see the exact event id in RabbitMq messages.

**Comment by NicolasDorier** [comment]
I don't put `JsonIgnore` easily, so there is probably a good reason I did so. I would prefer if we added it to a property of the message.

**Comment by farukterzioglu** [comment]
I was thinking to put it under RabbitMq message header as `BasicProperties.Headers[EventId]` (like CryptoCode) but I didn't get this exception for a long time, closing this.
