### ISSUE TITLE
Getting error with some Dash block: "Error while calling event handler"

### ISSUE THREAD

**Issue by farukterzioglu** [dgarage/NBXplorer#285]
Same as #271. Still getting this exception sometimes. Couldn't re-open the existing one.

**Comment by farukterzioglu** [comment]
```
info: Events:         DASH: New block 0000000000000003adfd9ef8b5b6823c42620ed246b77b50a498240125260f84 (1304074)
fail: Events:         Error while calling event handler
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at NBXplorer.Analytics.FingerprintDistribution.CalculateFingerprint(Transaction tx) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 176
   at NBXplorer.Analytics.FingerprintDistribution..ctor(Block block) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 86
   at NBXplorer.Analytics.FingerprintDistribution.Calculate(Block block) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 16
   at NBXplorer.Analytics.FingerprintHostedService.<StartAsync>b__7_0(RawBlockEvent evt) in /NBXplorer/NBXplorer/Analytics/FingerprintHostedService.cs:line 63
   at NBXplorer.EventAggregator.Publish[T](T evt, Boolean internalEvent) in /NBXplorer/NBXplorer/EventAggregator.cs:line 104
info: Events:         DASH: New block 000000000000000032645b847e8583f1112a380f8c0a6cad174bd1b7ca001660 (1304075)
fail: Events:         Error while calling event handler
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at NBXplorer.Analytics.FingerprintDistribution.CalculateFingerprint(Transaction tx) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 176
   at NBXplorer.Analytics.FingerprintDistribution..ctor(Block block) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 86
   at NBXplorer.Analytics.FingerprintDistribution.Calculate(Block block) in /NBXplorer/NBXplorer/Analytics/FingerprintDistribution.cs:line 16
   at NBXplorer.Analytics.FingerprintHostedService.<StartAsync>b__7_0(RawBlockEvent evt) in /NBXplorer/NBXplorer/Analytics/FingerprintHostedService.cs:line 63
   at NBXplorer.EventAggregator.Publish[T](T evt, Boolean internalEvent) in /NBXplorer/NBXplorer/EventAggregator.cs:line 104
info: Events:         DASH: New block 0000000000000001471d3da198b31290968515acbb59aef9256e6f881e825049 (1304076)
```
