### ISSUE TITLE
Exception while getting utxos: "An item with the same key has already been added."

### ISSUE THREAD

**Issue by farukterzioglu** [dgarage/NBXplorer#288]
While I try to get utxos, I am getting an exception as below, when a transaction (that one of my addresses received) is invalid with message "Transaction invalid: some outputs that it attempts to spend have been already spent or are no longer valid." and the other tx which spends those outputs is unconfirmed. 

```
System.ArgumentException: An item with the same key has already been added. Key: 25b34bf8a29323cfec620f8fd41c874eb6f679b9a1fa0283e6bcc8e5cdfc4568
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at NBXplorer.AnnotatedTransactionCollection..ctor(ICollection`1 transactions, TrackedSource trackedSource, SlimChain headerChain, Network network) in /NBXplorer
/NBXplorer/AnnotatedTransactionCollection.cs:line 158
   at NBXplorer.Controllers.MainController.GetAnnotatedTransactions(Repository repo, SlimChain chain, TrackedSource trackedSource, uint256 txId) in /NBXplorer/NBXp
lorer/Controllers/MainController.cs:line 957
   at NBXplorer.Controllers.MainController.GetUTXOs(String cryptoCode, DerivationStrategyBase derivationScheme, BitcoinAddress address) in /NBXplorer/NBXplorer/Con
trollers/MainController.cs:line 903
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executo
r, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionR
esultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask,
State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, S
cope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at NBXplorer.Startup.<>c__DisplayClass5_0.<<Configure>b__0>d.MoveNext() in /NBXplorer/NBXplorer/Startup.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Invalid tx: https://www.blockchain.com/btc/tx/25b34bf8a29323cfec620f8fd41c874eb6f679b9a1fa0283e6bcc8e5cdfc4568
Unconfirmed (as I wrote) tx: https://www.blockchain.com/btc/tx/2004eb1e6f6080176819ae49bccf8572f03831dc19d4136fdd242bfdd07ed5fc

**Invalid Tx**
![image](https://user-images.githubusercontent.com/476514/89110547-5369b780-d454-11ea-8763-ba4767b4d52f.png)

**Other Tx**
![image](https://user-images.githubusercontent.com/476514/89110549-595f9880-d454-11ea-8005-fddf93188dc8.png)

**Comment by farukterzioglu** [comment]
I made a quick fix on local to save the day, I wasn't able to get utxo list because of this. 
For now I am running as below, and hoping for no side effects.

![image](https://user-images.githubusercontent.com/476514/89111139-cc6c0d80-d45a-11ea-97f6-cd2193165076.png)

**Comment by NicolasDorier** [comment]
making a new version .40 thanks a lot for the report
