### ISSUE TITLE
Error while saving block in database : Invalid argument

### ISSUE THREAD

**Issue by farukterzioglu** [dgarage/NBXplorer#302]
We are getting an exception while saving recent Btc blocks, and this causes missing some block and we are getting missing-input exception while trying to spend already spent inputs.

NBXplorer running with lates commit.

Exception we got;
```
fail: Explorer:       BTC: Unhandled error while treating a message
fail: Explorer:       System.IO.IOException: Invalid argument
         at System.IO.FileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
         at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
         at DBTrie.Storage.FileStorage.Read(Int64 offset, Memory`1 output)
         at DBTrie.Storage.CacheStorage.FetchPage(Int32 p)
         at DBTrie.Storage.CacheStorage.Write(Int64 offset, ReadOnlyMemory`1 input)
         at DBTrie.Storage.StorageExtensions.WriteToEnd(IStorage storage, ReadOnlyMemory`1 input)
         at DBTrie.TrieModel.LTrieNode.Relocate(Int32 neededSlots)
         at DBTrie.TrieModel.LTrieNode.SetExternalValue(Byte label, ReadOnlyMemory`1 key, ReadOnlyMemory`1 value)
         at DBTrie.TrieModel.LTrieNode.SetValue(Nullable`1 linkLabel, ReadOnlyMemory`1 key, ReadOnlyMemory`1 value)
         at DBTrie.TrieModel.LTrie.SetValue(ReadOnlyMemory`1 key, ReadOnlyMemory`1 value, Boolean replace)
         at DBTrie.TrieModel.LTrie.SetValue(String key, ReadOnlyMemory`1 value, Boolean replace)
         at DBTrie.Table.Insert(String key, ReadOnlyMemory`1 value, Boolean replace)
         at NBXplorer.Repository.Index.Insert(String key, Byte[] value, Boolean replace) in /NBXplorer/NBXplorer/Repository.cs:line 355
         at NBXplorer.Repository.Index.Insert(Int64 key, Byte[] value) in /NBXplorer/NBXplorer/Repository.cs:line 350
         at NBXplorer.Repository.SaveEvent(NewEventBase evt) in /NBXplorer/NBXplorer/Repository.cs:line 558
         at NBXplorer.ExplorerBehavior.SaveMatches(TrackedTransaction[] matches, uint256 blockHash, DateTimeOffset now, Boolean fireEvents) in /NBXplorer/NBXplorer/Ex
plorerBehavior.cs:line 387
         at NBXplorer.ExplorerBehavior.SaveMatches(Transaction transaction, Boolean fireEvents) in /NBXplorer/NBXplorer/ExplorerBehavior.cs:line 346
         at NBXplorer.ExplorerBehavior.<>c__DisplayClass38_0.<<Run>b__0>d.MoveNext() in /NBXplorer/NBXplorer/ExplorerBehavior.cs:line 278fail: Explorer:       BTC: Unhandled error while treating a message
fail: Explorer:       System.IO.IOException: Invalid argument
         at System.IO.FileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
         at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
         at DBTrie.Storage.FileStorage.Read(Int64 offset, Memory`1 output)
         at DBTrie.Storage.CacheStorage.FetchPage(Int32 p)
         at DBTrie.Storage.CacheStorage.Write(Int64 offset, ReadOnlyMemory`1 input)
         at DBTrie.Storage.StorageExtensions.WriteToEnd(IStorage storage, ReadOnlyMemory`1 input)
         at DBTrie.TrieModel.LTrieNode.Relocate(Int32 neededSlots)
         at DBTrie.TrieModel.LTrieNode.SetExternalValue(Byte label, ReadOnlyMemory`1 key, ReadOnlyMemory`1 value)
         at DBTrie.TrieModel.LTrieNode.SetValue(Nullable`1 linkLabel, ReadOnlyMemory`1 key, ReadOnlyMemory`1 value)
         at DBTrie.TrieModel.LTrie.SetValue(ReadOnlyMemory`1 key, ReadOnlyMemory`1 value, Boolean replace)
         at DBTrie.TrieModel.LTrie.SetValue(String key, ReadOnlyMemory`1 value, Boolean replace)
         at DBTrie.Table.Insert(String key, ReadOnlyMemory`1 value, Boolean replace)
         at NBXplorer.Repository.Index.Insert(String key, Byte[] value, Boolean replace) in /NBXplorer/NBXplorer/Repository.cs:line 355
         at NBXplorer.Repository.Index.Insert(Int64 key, Byte[] value) in /NBXplorer/NBXplorer/Repository.cs:line 350
         at NBXplorer.Repository.SaveEvent(NewEventBase evt) in /NBXplorer/NBXplorer/Repository.cs:line 558
         at NBXplorer.ExplorerBehavior.SaveMatches(TrackedTransaction[] matches, uint256 blockHash, DateTimeOffset now, Boolean fireEvents) in /NBXplorer/NBXplorer/Ex
plorerBehavior.cs:line 387
         at NBXplorer.ExplorerBehavior.SaveMatches(Transaction transaction, Boolean fireEvents) in /NBXplorer/NBXplorer/ExplorerBehavior.cs:line 346
         at NBXplorer.ExplorerBehavior.<>c__DisplayClass38_0.<<Run>b__0>d.MoveNext() in /NBXplorer/NBXplorer/ExplorerBehavior.cs:line 278
 ```

**Comment by NicolasDorier** [comment]
DBTrie, a dependency to NBXPlorer had a critical bug which result in a corrupted install which can't restart. Fixed in v2.2.7.
This impact only big instances.

Thanks for the report!
