### ISSUE TITLE
NBXplorer connected to the remote node but failed to handhsake via P2P.

### ISSUE THREAD

**Issue by lbphp** [dgarage/NBXplorer#310]
```
./run.sh --network=testnet --chains=ltc --ltcrpcuser=xxx --ltcrpcpassword=yyy
info: Configuration:  Data Directory: /root/.nbxplorer/TestNet
info: Configuration:  Configuration File: /root/.nbxplorer/TestNet/settings.config
info: Configuration:  Network: Testnet
info: Configuration:  Supported chains: LTC
info: Configuration:  DBCache: 50 MB
info: Configuration:  Network: Testnet
info: Configuration:  Supported chains: LTC
info: Configuration:  DBCache: 50 MB
info: Explorer:       Defragmenting transaction tables...
info: Explorer:       Defragmentation succeed, 0 bytes saved
info: Explorer:       Applying migration if needed, do not close NBXplorer...
info: Configuration:  LTC: Testing RPC connection to http://localhost:19332/
Hosting environment: Production
Content root path: /root/NBXplorer/NBXplorer/bin/Release/netcoreapp3.1/
Now listening on: http://127.0.0.1:24445
Application started. Press Ctrl+C to shut down.
info: Configuration:  LTC: RPC connection successful
info: Configuration:  LTC: Full node version detected: 180100
info: Configuration:  LTC: Trying to connect via the P2P protocol to trusted node (127.0.0.1:19335)...
info: Explorer:       LTC: TCP Connection succeed, handshaking...
warn: Explorer:       LTC: NBXplorer connected to the remote node but failed to handhsake via P2P.
      Your node may not have an available connection slot, or you may try to connect to the wrong node. (ie, trying to connect to a LTC node on the BTC configuration).
      To make sure your node have an available connection slot, use "whitebind" or "whitelist" in your node configuration. (typically whitelist=127.0.0.1 if NBXplorer and the node are on the same machine.)

fail: Configuration:  LTC: Unhandled in Waiter loop
System.InvalidOperationException: The node is not in a connected state
   at NBitcoin.Protocol.NodeListener.ReceivePayload[TPayload](CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.VersionHandshake(NodeRequirement requirements, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.VersionHandshake(CancellationToken cancellationToken)
   at NBXplorer.BitcoinDWaiter.ConnectToBitcoinD(CancellationToken cancellation) in /root/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 462
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /root/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 315
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, Signaler tick) in /root/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 207
info: Configuration:  LTC: Testing again in 5 seconds

```

Hi, what's causing this? I have only Litecoin Core on the server and i have enabled only ltc in the `chains `parameter of NBXplorer

**Comment by lbphp** [comment]
The rpc credentials seem correct:

```
 litecoin-cli -rpcuser=xxx -rpcpassword=yyy getbalance
0.00000000 
```

**Comment by lbphp** [comment]
I have also tried to add whitelist=127.0.0.1 to my litecoin.conf file but the error persists

Litecoin.conf:
```

server=1
txindex=1
rpcallowip=127.0.0.1
rpcuser=xxx
rpcpassword=yyy
rpcbind=127.0.0.1
rest=1
daemon=1
datadir=/root/.litecoin/data
rpcworkqueue=128
maxmempool=150
dbcache=20
maxsigcachesize=4
maxconnections=4
rpcthreads=1
testnet=1
printtoconsole=1
addresstype=bech32
whitelist=127.0.0.1
```

**Comment by lbphp** [comment]
SOLVED
the issue was with maxconnections=4 setting in the .conf. Just commented it
