### ISSUE TITLE
Configuration:  BTC: Unhandled in Waiter loop

### ISSUE THREAD

**Issue by thestick613** [dgarage/NBXplorer#312]
```
Apr 17 15:42:21 btcpay.local dotnet[5221]: info: Configuration:  BTC: Loading chain from cache...
Apr 17 15:42:22 btcpay.local dotnet[5221]: info: Configuration:  BTC: Height: 679548
Apr 17 15:42:22 btcpay.local dotnet[5221]: info: Configuration:  BTC: Trying to connect via the P2P protocol to trusted node (x.x.x.x:8333)...
Apr 17 15:42:22 btcpay.local dotnet[5221]: info: Explorer:       BTC: TCP Connection succeed, handshaking...
Apr 17 15:42:22 btcpay.local dotnet[5221]: info: Explorer:       BTC: Handshaked
Apr 17 15:42:22 btcpay.local dotnet[5221]: info: Configuration:  BTC: Loading chain from node
Apr 17 15:42:22 btcpay.local dotnet[5221]: info: Explorer:       BTC: Loading chain...
Apr 17 15:42:22 btcpay.local dotnet[5221]: info: Explorer:       BTC: Chain loaded
Apr 17 15:42:22 btcpay.local dotnet[5221]: fail: Configuration:  BTC: Unhandled in Waiter loop
Apr 17 15:42:22 btcpay.local dotnet[5221]: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
Apr 17 15:42:22 btcpay.local dotnet[5221]:    at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
Apr 17 15:42:22 btcpay.local dotnet[5221]:    at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
Apr 17 15:42:22 btcpay.local dotnet[5221]:    at NBitcoin.RPC.RPCClient.GetPeersInfoAsync()
Apr 17 15:42:22 btcpay.local dotnet[5221]:    at NBXplorer.BitcoinDWaiter.ConnectToBitcoinD(CancellationToken cancellation) in /home/user/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 547
Apr 17 15:42:22 btcpay.local dotnet[5221]:    at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /home/user/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 378
Apr 17 15:42:22 btcpay.local dotnet[5221]:    at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, Signaler tick) in /home/user/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 207
Apr 17 15:42:22 btcpay.local dotnet[5221]: info: Configuration:  BTC: Testing again in 60 seconds

```

**Comment by NicolasDorier** [comment]
what version of NBX? what version of bitcoind?

**Comment by kallerosenbaum** [comment]
I also see this after I upgraded btcpayserver to v1.1.0, nbxplorer to v2.1.9 and bitcoind to 0.21.1. nbxplorer is built from source on the same machine.

**Comment by kallerosenbaum** [comment]
Ignore my previous comment. I hadn't updated to the latest version 2.1.51. I fooled myself by lexicographical tag sorting when checking out the "latest" version so I got 2.1.9. It works fine on 2.1.51. Maybe that's what @thestick613 did too?

**Comment by NicolasDorier** [comment]
hey sorry I dropped the ball on this issue. Yes, this was a breaking change in bitcoin core which happened, which had been fixed in new versions of nbx.

Please feel free to reopen @thestick613 if that's not it.
