### ISSUE TITLE
Unable to create PSBT

### ISSUE THREAD

**Issue by golyalpha** [dgarage/NBXplorer#357]
When trying to create a PSBT via NBXplorer, I get the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NBXplorer.Controllers.MainController.CreatePSBT(NBXplorerNetwork network, DerivationStrategyBase strategy, JObject body, IUTXOService utxoService) in /source/NBXplorer/Controllers/MainController.PSBT.cs:line 227
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

This happens, for example, when trying to send funds via the BTCPayServer WebUI.

Running from docker image `nicolasdorier/nbxplorer:2.3.4`

**Comment by NicolasDorier** [comment]
Thank you, checking it now.

**Comment by NicolasDorier** [comment]
I bumped to 2.1.5, can you give one more try?

**Comment by NicolasDorier** [comment]
I am surprised about this bug though. What I did may have fixed it, but I don't understand the root cause yet.

**Comment by golyalpha** [comment]
Nope, looks to be same exact traceback in 2.1.5

**Comment by NicolasDorier** [comment]
@golyalpha did you already made a transaction with this wallet before the 2.3.4 ?

**Comment by golyalpha** [comment]
Yes, way before.

**Comment by NicolasDorier** [comment]
I need to go to bed, will take a look at it in priority tomorrow morning. Maybe something has gone wrong with the migration, I will need to find out.
Aside from this, your balance seems correct and transactions appears properly?

**Comment by golyalpha** [comment]
Yeah, everything else is fine.

**Comment by NicolasDorier** [comment]
@golyalpha are you able to dig a bit?

Can you fetch your derivation scheme in the settings of your wallet (http://hack0.local/stores/{storeid}/onchain/BTC/settings)

Then connect to your database:

```bash
 docker exec -ti generated_postgres_1 psql -U postgres -d nbxplorermainnet
```

Then you should be able to run this command line. (replace `xpub...`)

```SQL
SELECT s.script, s.addr, nbxv1_get_keypath(d.metadata , ds.idx) keypath, ds.metadata->>'redeem' redeem FROM descriptors_scripts ds
JOIN scripts s USING (code, script)
JOIN descriptors d USING (code, descriptor)
WHERE ds.code='BTC' AND ds.descriptor=nbxv1_get_descriptor_id('BTC', 'xpub...', 'Change') AND ds.used='f'
ORDER BY ds.idx;
```
Do you see any row there?

Then can you tell me the count here
```SQL
SELECT COUNT(*) FROM descriptors_scripts ds
JOIN scripts s USING (code, script)
JOIN descriptors d USING (code, descriptor)
WHERE ds.code='BTC' AND ds.descriptor=nbxv1_get_descriptor_id('BTC', 'xpub...', 'Change')
ORDER BY ds.idx;
```

Then can you check this (replace `xpub...`).
```SQL
SELECT next_idx, gap FROM descriptors d
WHERE d.code='BTC' AND d.descriptor=nbxv1_get_descriptor_id('BTC', 'xpub...', 'Change') ;
```

**Comment by NicolasDorier** [comment]
I found on our mainnet database some xpubs that may have the same problem. I am unsure why yet... will find out.

**Comment by NicolasDorier** [comment]
@golyalpha try 2.3.6

**Comment by golyalpha** [comment]
Yeah, it works now. Thanks.
