### ISSUE TITLE
Can't connect to DASH 18.0.1 after V18 hard fork (2022-09-13)

### ISSUE THREAD

**Issue by simonlucalandi** [dgarage/NBXplorer#376]
This is what the log says:

```
fail: NBXplorer.Indexer.DASH: Unhandled exception in the indexer, retrying in 60 seconds
System.InvalidOperationException: The node is not in a connected state
   at NBitcoin.Protocol.NodeListener.ReceivePayload[TPayload](CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.VersionHandshake(NodeRequirement requirements, CancellationToken cancellationToken)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.ConnectNode(CancellationToken token, Boolean forceRestart) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 216
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 76
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 55
```

The issue seams to be caused by the NBitcoin library using an obsolete version.
This is what the `dash core` says, after enabling the full logging:

```
2022-09-18T06:16:52Z peer=3593 using obsolete version 70213; disconnecting
2022-09-18T06:16:52Z sending reject (42 bytes) peer=3593
2022-09-18T06:16:52Z ProcessMessages(version, 115 bytes) FAILED peer=3593
2022-09-18T06:16:52Z disconnecting peer=3593
```

I'm going to open an issue on the NBitcoin library, but I think it is worth mentioning here.

**Comment by NicolasDorier** [comment]
update your version of NBXplorer, and it should work

**Comment by simonlucalandi** [comment]
I forgot to mention the version on NBXplorer I used: [v2.3.34](https://github.com/dgarage/NBXplorer/releases/tag/v2.3.34)

Do you mean to update to latest master?

**Comment by NicolasDorier** [comment]
yes, I fixed it today for good.
