### ISSUE TITLE
NBXplorer error - duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by PraiaBitcoin** [dgarage/NBXplorer#382]
This morning, our BTCPayServer runninon MyNodeBtc gets stuck on block 762359

We are running NBX v2.3.44 (nicolasdorier/nbxplorer:2.3.44) and BtcPay 1.6.12

Here is the error 
```
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 10 seconds
Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "nbxv1_evts_pkey"

```

Relevant log part of Btc pay
```
2022-11-09 03:14:03.965 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2022-11-09 03:14:03.965 +00:00 [INF] TorServices successfully exited...
2022-11-09 03:14:03.966 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2022-11-09 03:14:03.967 +00:00 [ERR] Error while connecting to WebSocket of NBXplorer (BTC)
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at NBXplorer.WebsocketMessageListener.NextMessageAsync(CancellationToken cancellation)
   at BTCPayServer.Payments.Bitcoin.NBXplorerListener.Listen(BTCPayWallet wallet) in /source/BTCPayServer/Payments/Bitcoin/NBXplorerListener.cs:line 142
2022-11-09 03:14:03.968 +00:00 [INF] Disconnected from WebSocket of NBXplorer (BTC)
2022-11-09 03:14:03.973 +00:00 [INF] PullPaymentHostedService successfully exited...
2022-11-09 03:14:03.974 +00:00 [INF] NBXplorerListener successfully exited...
2022-11-09 03:14:03.975 +00:00 [INF] LightningListener successfully exited...
2022-11-09 03:14:03.975 +00:00 [INF] LightningPendingPayoutListener successfully exited...
2022-11-09 03:14:03.981 +00:00 [INF] Stop watching invoices
2022-11-09 03:14:03.988 +00:00 [INF] RatesHostedService successfully exited...
2022-11-09 03:14:03.994 +00:00 [INF] DynamicDnsHostedService successfully exited...
2022-11-09 03:14:03.997 +00:00 [INF] NewVersionCheckerHostedService successfully exited...
2022-11-09 03:14:03.997 +00:00 [INF] DbMigrationsHostedService successfully exited...
2022-11-09 03:14:04.000 +00:00 [INF] LightningAutomatedPayoutProcessor successfully exited...
2022-11-09 03:14:12.862 +00:00 [INF] Root Path: /
2022-11-09 03:14:13.448 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
```

**Comment by NicolasDorier** [comment]
@PraiaBitcoin this is strange error. Are you using the docker deployment? Does it continuously throw this error or did it just happened once?

**Comment by NicolasDorier** [comment]
This error is strange, I suspect the table `nbxv1_evts_ids` hasn't been properly migrated. I never saw that happening, but I don't see how it would have been an issue only on `MyNodeBtc`. 

Are you tech savvy enough to run sql queries against the database?

If so, I would like you run the following 

`SELECT * FROM nbxv1_evts_ids`

And 

`SELECT code, MAX(id) FROM nbxv1_evts GROUP BY code;`

**Comment by PraiaBitcoin** [comment]
Hi Nicolas

The version is `postgres:13.7 `
I'm not a tech-savvy, but if you tell me the sequence of commands, I can do. 

I had this problem in the past but I think is different now. I just reinstalled and back to work, but now, I did it twice and the issue persists. 

Here is the full log:
```
[40m[32minfo[39m[22m[49m: NBXplorer.Events: BTC: Node state changed: NBXplorerSynching => NotStarted
[40m[32minfo[39m[22m[49m: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
[40m[32minfo[39m[22m[49m: NBXplorer.Indexer.BTC: Handshaked
[40m[32minfo[39m[22m[49m: NBXplorer.Indexer.BTC: Testing RPC connection to http://host.docker.internal:8332/
[40m[32minfo[39m[22m[49m: NBXplorer.Indexer.BTC: RPC connection successful
[40m[32minfo[39m[22m[49m: NBXplorer.Indexer.BTC: Full node version detected: 230000
[40m[32minfo[39m[22m[49m: NBXplorer.Indexer.BTC: NBXplorer is correctly whitelisted by the node
[40m[32minfo[39m[22m[49m: NBXplorer.Events: BTC: Node state changed: NotStarted => NBXplorerSynching
[41m[30mfail[39m[22m[49m: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 60 seconds
Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "nbxv1_evts_pkey"

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|44_0(NpgsqlConnector connector, Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken)
   at Dapper.SqlMapper.ExecuteScalarImplAsync[T](IDbConnection cnn, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 1219
   at NBXplorer.Backends.Postgres.PostgresRepository.SaveEvent(DbConnectionHelper conn, NewEventBase evt) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 1004
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.SaveMatches(DbConnectionHelper conn, List`1 transactions, SlimChainedBlock slimChainedBlock, Boolean fireEvents) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 382
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.SaveMatches(DbConnectionHelper conn, Block block, SlimChainedBlock slimChainedBlock) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 360
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 113
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 103
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 164
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 77
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 55
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "nbxv1_evts_pkey"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: public
    TableName: nbxv1_evts
    ConstraintName: nbxv1_evts_pkey
    File: nbtinsert.c
    Line: 649
    Routine: _bt_check_unique

```
An easy fix, would be great. I need to make BTCPayServer back to work as soon as possible. 



Thank you very much by helping us

**Comment by PraiaBitcoin** [comment]
Here is the result

![image](https://user-images.githubusercontent.com/94765727/201441927-cabf67de-e15c-430e-b23c-bba1ded70c28.png)

I used this command to get the results
`docker exec -it $(docker ps -a -q -f "name=postgres_1") psql -U postgres -d nbxplorermainnet
`

**Comment by tehelsper** [comment]
> Also, may you ask to the `MyNodeBtc` guys, if possible, when did they migrated NBXplorer and whether other users reports the same issue?

I looked into how BTCPay gets setup and I may be doing something wrong that prevents upgrades from going smoothly in all cases. On upgrades, it actually re-runs the setup script in all cases rather than btcpay-setup.sh for initial install and btcpay-update.sh on upgrades. Could that be causing issues with the database?

I had been using the setup script so that I can easily control the exact version getting installed by setting the BTCPAY_IMAGE variable.

**Comment by NicolasDorier** [comment]
@PraiaBitcoin updating the `nbxv1_evts_ids` is the right workaround, there is no downside to it.

**Comment by NicolasDorier** [comment]
Frankly, @tehelsper I don't see anything somebody could have done to end up with this situation. This is really weird.

**Comment by NicolasDorier** [comment]
@PraiaBitcoin did this bug happened after a btcpay update?
