### ISSUE TITLE
Connecting to a remote (LAN) BTC node

### ISSUE THREAD

**Issue by cypcz** [dgarage/NBXplorer#420]
Hello.

I'm struggling with connecting NBXplorer to a remote BTC node that is on the same LAN. I can confirm that my BTC node is running and accessible - I have other service on LAN that is able to connect to it over RPC without any issues.

### nbxplorer.config
```
### Database ###
postgres=User ID=nbxplorer;Password=[redacted];Application Name=nbxplorer;MaxPoolSize=20;Host=localhost;Port=5432;Database=nbxplorer;

### BTC ###
btcrpcurl=http://192.168.4.12:8332
btcrpcuser=[redacted]
btcrpcpassword=[redacted]
```

### start command
`sudo ./run.sh --conf=/home/[redacted]/NBXplorer/nbxplorer.config`

### output
```
info: Configuration:  Data Directory: /root/.nbxplorer/Main
info: Configuration:  Configuration File: /home/[redacted]/NBXplorer/nbxplorer.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  DBCache: 50 MB
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  DBCache: 50 MB
info: NBXplorer.DatabaseSetup: Postgres services activated
Hosting environment: Production
Content root path: /home/[redacted]/NBXplorer/NBXplorer/bin/Release/net6.0/
Now listening on: http://127.0.0.1:24444
Application started. Press Ctrl+C to shut down.
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 0 seconds
System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.ConnectNode(CancellationToken token, Boolean forceRestart) in /home/[redacted]/NBXplorer/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 236
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /home/[redacted]/NBXplorer/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 77
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /home/[redacted]/NBXplorer/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 56
```

I'm not even sure if the error points to issues connecting to a BTC node. I don't see anything in BTC node logs when I try to run NBXplorer.

Any idea is greatly appreciated! Thank you.

**Comment by cypcz** [comment]
`var node = await Node.ConnectAsync(network.NBitcoinNetwork, ChainConfiguration.NodeEndpoint, new NodeConnectionParameters()`

This line throws the exception.

**Comment by NicolasDorier** [comment]
`Connection refused` means that the remote machine `192.168.4.12` probably have a firewall.

**Comment by cypcz** [comment]
Thanks for the reply @NicolasDorier. `192.168.4.12` is my nginx proxy that forwards the request to BTC node.

Querying the BTC node via RPC from machine where I'm running NBXplorer works fine.

`curl -u [redacted]:[redacted]-H 'content-type: text/plain;' --data-binary '{"jsonrpc":"1.0","id":"test","method":"getblockchaininfo","params":[]}' http://192.168.4.12:8332`

```
{
   "result":{
      "chain":"main",
      "blocks":796525,
      "headers":796525,
      "bestblockhash":"00000000000000000005257003e2aeac195ad8f5e1bab3e5a4667ae727d87847",
      "difficulty":50646206431058.09,
      "time":1688109430,
      "mediantime":1688104309,
      "verificationprogress":0.9999996011644466,
      "initialblockdownload":false,
      "chainwork":"00000000000000000000000000000000000000004d43c4fa9b18035d549d80f8",
      "size_on_disk":558544800747,
      "pruned":false,
      "warnings":""
   },
   "error":null,
   "id":"test"
}
```

**Comment by cypcz** [comment]
It works. Thank you very much. 

I had no idea there is something like P2P connection to BTC node and that NBXplorer is using both RPC and P2P. We learn something every day :)
