### ISSUE TITLE
Minimal manual setup instuctions are outdated

### ISSUE THREAD

**Issue by ikuuse** [dgarage/NBXplorer#462]
Hello,

I'm trying to set up a minimal manual setup on a Windows machine. I have Bitcoin node running successfully but cannot get NBXplorer running with default settings. 

settings.config says
####If Bitcoin Core is running with default settings, you should not need to modify this file#### <-- not true anymore

NBXplorer is defaulting to port 39383 and postgres default port is 5432, which one to use?

When I run simple "dotnet run" I get a message 
Unhandled exception. Npgsql.NpgsqlException (0x80004005): No password has been provided but the backend requires one (in SASL/SCRAM-SHA-256)

A password was required by postgres. 

Then I run the command

dotnet run --chains=btc --network=regtest --postgres "User ID=postgres;Password=postgres;Host=127.0.0.1;Port=39383;Database=nbxplorer"

Getting error

info: NBXplorer.DatabaseSetup: Postgres services activated
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 0 seconds
System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)

I already tried to follow the extended deployment instructions at https://docs.btcpayserver.org/Deployment/ManualDeploymentExtended/

But the postgres instructions are invalid. 

Can anybody tell what's wrong? The current instructions are outdated.

**Comment by ikuuse** [comment]
Similar issue with the Docker, when running it unmodified

2024-04-02 22:38:50 fail: Configuration:  You need to select your backend implementation. There is two choices, PostgresSQL and DBTrie.
2024-04-02 22:38:50         * To use postgres, please use --postgres "..." (or NBXPLORER_POSTGRES="...") with a postgres connection string (see https://www.connectionstrings.com/postgresql/)
2024-04-02 22:38:50         * To use DBTrie, use --dbtrie (or NBXPLORER_DBTRIE=1). This backend is deprecated, only use if you haven't yet migrated. For more information about how to migrate, see https://github.com/dgarage/NBXplorer/tree/master/docs/Postgres-Migration.md

**Comment by NicolasDorier** [comment]
It's a problem of configuration of Postgres. Please configure a password for postgres or use `POSTGRES_HOST_AUTH_METHOD: trust`. I can't hand hold you how to do this on Windows because I don't know.

If you want to develop, I advise to just use postgres on docker.

**Comment by ikuuse** [comment]
I tried with password, didn't work either. I tried to use on docker as well but couldn't figure out the Environment variables. I wish there was a simple copy&paste line I could use. Thank you

**Comment by mjlamb** [comment]
I have found using the follow for nbxplorer to run fine. I use the nbxplorer config file with lines.

settings.config file

## RPC Connection to your node
btc.rpc.url=http://127.0.0.1:8332/
btc.rpc.user=[yourUsername]
btc.rpc.password=[yourPassword]

## DATABASE Connection
postgres="User ID=postgres;password=**********;Host=127.0.0.1;Port=5432;Database=nbxplorer;"


and run the nbxplorer via command

dotnet run --no-launch-profile --port=20333 -c Release --project NBXplorer.csproj --exposerpc=1
