### ISSUE TITLE
[feature]: support mutinynet

### ISSUE THREAD

**Issue by chrisguida** [dgarage/NBXplorer#472]
Voltage has [support for mutinynet now](https://www.voltage.cloud/blog/mutinynet-now-available-on-voltage), but I can't seem to get btcpay server working on a nix-bitcoin node that otherwise supports mutinynet.

NBXplorer is choking on downloading the headers, I imagine this is because it is unaware of the special custom signet configuration required for mutinynet (see bottom of https://faucet.mutinynet.com):

![image](https://github.com/dgarage/NBXplorer/assets/7445670/6a374c4f-b64e-4b05-a4ae-0bd2c25e262f)

My btcpay instance is stuck like this for now:
![image](https://github.com/dgarage/NBXplorer/assets/7445670/a6db2ae2-98c1-4ae3-a985-27d427c55431)

NBXplorer logs look like this:

```
Jun 29 21:03:34 nix-enchilada nbxplorer[9003]: System.InvalidOperationException: The node is not in a connected state
Jun 29 21:03:34 nix-enchilada nbxplorer[9003]:    at NBitcoin.Protocol.NodeListener.ReceivePayload[TPayload](CancellationToken cancellationToken)
Jun 29 21:03:34 nix-enchilada nbxplorer[9003]:    at NBitcoin.Protocol.Node.VersionHandshake(NodeRequirement requirements, CancellationToken cancellationToken)
Jun 29 21:03:34 nix-enchilada nbxplorer[9003]:    at NBitcoin.Protocol.Node.VersionHandshake(CancellationToken cancellationToken)
Jun 29 21:03:34 nix-enchilada nbxplorer[9003]:    at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.ConnectNode(CancellationToken token) in /build/source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 305
Jun 29 21:03:34 nix-enchilada nbxplorer[9003]:    at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /build/source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 150
Jun 29 21:03:34 nix-enchilada nbxplorer[9003]:    at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /build/source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 99
Jun 29 21:03:59 nix-enchilada nbxplorer[9003]: info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
Jun 29 21:03:59 nix-enchilada nbxplorer[9003]: fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 30 seconds
Jun 29 21:03:59 nix-enchilada nbxplorer[9003]: System.InvalidOperationException: The node is not in a connected state
Jun 29 21:03:59 nix-enchilada nbxplorer[9003]:    at NBitcoin.Protocol.NodeListener.ReceivePayload[TPayload](CancellationToken cancellationToken)
Jun 29 21:03:59 nix-enchilada nbxplorer[9003]:    at NBitcoin.Protocol.Node.VersionHandshake(NodeRequirement requirements, CancellationToken cancellationToken)
Jun 29 21:03:59 nix-enchilada nbxplorer[9003]:    at NBitcoin.Protocol.Node.VersionHandshake(CancellationToken cancellationToken)
Jun 29 21:03:59 nix-enchilada nbxplorer[9003]:    at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.ConnectNode(CancellationToken token) in /build/source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 305
Jun 29 21:03:59 nix-enchilada nbxplorer[9003]:    at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /build/source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 150
Jun 29 21:03:59 nix-enchilada nbxplorer[9003]:    at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /build/source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 99
```

**Comment by chrisguida** [comment]
It would be great if someone could show me how to enable trace logging so I can maybe hack around this

**Comment by Kukks** [comment]
Mutiny support was merged: https://github.com/dgarage/NBXplorer/pull/474

**Comment by chrisguida** [comment]
@Kukks SWEET! Thanks man!!!
