### ISSUE TITLE
Cannot connect to Bitcoin node 

### ISSUE THREAD

**Issue by gus4rs** [dgarage/NBXplorer#476]
Using ```master``` version on Fedora Linux, Bitcoin Core ```v27.1```

Config stored at ```/home/.user/settings.config```
```
btc.rpc.url=http://127.0.0.1:8332
btc.rpc.user=bitcoin
btc.rpc.password=bitcoin
port=24445
mainnet=1
postgres="User ID=satoshi;Password=satoshi;Host=127.0.0.1;Database=nbxplorer"
``` 

Credential are correct, the command below works:

```
# bitcoin-cli -rpcpassword=bitcoin -rpcuser=bitcoin uptime 
97622
```

NBXplorer fails to connect to the node:

```
➜  NBXplorer git:(master) ./run.sh -c /home/user/settings.config                       
info: Configuration:  Data Directory: /home/user/.nbxplorer/Main
info: Configuration:  Configuration File: /home/user/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: NBXplorer.DatabaseSetup: Postgres services activated
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 0 seconds
System.InvalidOperationException: The node is not in a connected state
   at NBitcoin.Protocol.NodeListener.ReceivePayload[TPayload](CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.VersionHandshake(NodeRequirement requirements, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.VersionHandshake(CancellationToken cancellationToken)
   at NBXplorer.Backend.Indexer.ConnectNode(CancellationToken token) in /home/user/NBXplorer/NBXplorer/Backend/Indexer.cs:line 302
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /home/user/NBXplorer/NBXplorer/Backend/Indexer.cs:line 147
   at NBXplorer.Backend.Indexer.IndexerLoop() in /home/user/NBXplorer/NBXplorer/Backend/Indexer.cs:line 96
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 5 seconds
System.InvalidOperationException: The node is not in a connected state
   at NBitcoin.Protocol.NodeListener.ReceivePayload[TPayload](CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.VersionHandshake(NodeRequirement requirements, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.VersionHandshake(CancellationToken cancellationToken)
   at NBXplorer.Backend.Indexer.ConnectNode(CancellationToken token) in /home/user/NBXplorer/NBXplorer/Backend/Indexer.cs:line 302
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /home/user/NBXplorer/NBXplorer/Backend/Indexer.cs:line 147
   at NBXplorer.Backend.Indexer.IndexerLoop() in /home/user/NBXplorer/NBXplorer/Backend/Indexer.cs:line 96
Hosting environment: Production
Content root path: /home/user/NBXplorer/NBXplorer/bin/Release/net8.0/
Now listening on: http://127.0.0.1:24445
Application started. Press Ctrl+C to shut down.
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 10 seconds
System.InvalidOperationException: The node is not in a connected state
   at NBitcoin.Protocol.NodeListener.ReceivePayload[TPayload](CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.VersionHandshake(NodeRequirement requirements, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.VersionHandshake(CancellationToken cancellationToken)
   at NBXplorer.Backend.Indexer.ConnectNode(CancellationToken token) 
   ```

**Comment by gus4rs** [comment]
For some bizarre reason, the node 127.0.0.1 was banned by Bitcoin Core:

```
➜  NBXplorer git:(master) ✗ bitcoin-cli -rpcpassword=bitcoin -rpcuser=bitcoin listbanned
[
  {
    "address": "127.0.0.1/32",
    "ban_created": 1703601602,
    "banned_until": 1893456000,
    "ban_duration": 189854398,
    "time_remaining": 168328157
  },
]
```

So once I clear the ban list, it started working:

```
➜  NBXplorer git:(master) ✗ bitcoin-cli -rpcpassword=bitcoin -rpcuser=bitcoin clearbanned
```

Lost 1h I will never get back 
🤡
