### ISSUE TITLE
why port 39382 and not 5432 for postgres (and other questions regarding the manual)? 

### ISSUE THREAD

**Issue by kosuodhmwa** [dgarage/NBXplorer#498]
this: 

./run.sh --chains=btc --network=regtest --postgres "User ID=postgres;Host=127.0.0.1;Port=39382;Database=nbxplorer"

**Comment by kosuodhmwa** [comment]
when i try start

root@debian12-btc-node:~/NBXplorer# ./run.sh --chains=btc --network=regtest --postgres "User ID=postgres;Host=127.0.0.1;Port=39382;Database=nbxplorer"
info: Configuration:  NBXplorer version 2.5.16
Specify --help for a list of available options and commands.
fail: Explorer:
      Unrecognized command or argument 'ID=postgres;Host=127.0.0.1;Port=39382;Database=nbxplorer'
root@debian12-btc-node:~/NBXplorer#



OR


root@debian12-btc-node:~/NBXplorer# ./run.sh --chains=btc --network=regtest --postgres "User ID=postgres;Host=127.0.0.1;Port=5432;Database=nbxplorer"
info: Configuration:  NBXplorer version 2.5.16
Specify --help for a list of available options and commands.
fail: Explorer:
      Unrecognized command or argument 'ID=postgres;Host=127.0.0.1;Port=5432;Database=nbxplorer'
root@debian12-btc-node:~/NBXplorer#

**Comment by kosuodhmwa** [comment]
hmmmmmmm.... same situation, other product: https://github.com/btcpayserver/btcpayserver/issues/375

**Comment by kosuodhmwa** [comment]
because that does not work i wann use config file... but there does not seem to be a postgresql thing there...

:~/.nbxplorer/Main/settings.config

**Comment by kosuodhmwa** [comment]
now i added that line in file:

postgres="User ID=postgres;Host=127.0.0.1;Port=39382;Database=nbxplorer"


output still:

root@debian12-btc-node:~/NBXplorer# ./run.sh --chains=btc --network=regtest
info: Configuration:  NBXplorer version 2.5.16
info: Configuration:  Data Directory: /root/.nbxplorer/RegTest
info: Configuration:  Configuration File: /root/.nbxplorer/RegTest/settings.config
info: Configuration:  Network: Regtest
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Regtest
info: Configuration:  Supported chains: BTC
fail: Configuration:  **POSTGRES is required**
root@debian12-btc-node:~/NBXplorer#

**Comment by kosuodhmwa** [comment]
**same result with non-double quotes in config file:**

postgres='User ID=postgres;Host=127.0.0.1;Port=39382;Database=nbxplorer'


out:

`root@debian12-btc-node:~/NBXplorer# ./run.sh --chains=btc --network=regtest
info: Configuration:  NBXplorer version 2.5.16
info: Configuration:  Data Directory: /root/.nbxplorer/RegTest
info: Configuration:  Configuration File: /root/.nbxplorer/RegTest/settings.config
info: Configuration:  Network: Regtest
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Regtest
info: Configuration:  Supported chains: BTC
fail: Configuration:  POSTGRES is required`

**Comment by kosuodhmwa** [comment]
this 
![image](https://github.com/user-attachments/assets/7bd7c4f4-1f9a-4383-9756-8deae3ab8f8d)

**Comment by kosuodhmwa** [comment]
also not work with that in config file: 

host=127.0.0.1
port=39382
database=nbxplorer



running command:
./run.sh --chains=btc --network=regtest

(without db params)

**Comment by kosuodhmwa** [comment]
alternatively - but also an error:

`
root@debian12-btc-node:~/NBXplorer# dotnet run --no-launch-profile --no-build -c Release --project "NBXplorer/NBXplorer.csproj" --postgres "User ID=postgres;Host=postgres;Port=5432;Database=nbxplorer"
info: Configuration:  NBXplorer version 2.5.16
info: Configuration:  Data Directory: /root/.nbxplorer/Main
info: Configuration:  Configuration File: /root/.nbxplorer/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: NBXplorer.DatabaseSetup: Postgres services activated
Unhandled exception. System.Net.Sockets.SocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, Nullable`1 startingTimestamp)
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s, Int64 startingTimestamp)
   at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Npgsql.TaskTimeoutAndCancellation.ExecuteAsync(Func`2 getTaskFunc, NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.TaskTimeoutAndCancellation.ExecuteAsync[TResult](Func`2 getTaskFunc, NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
   at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|213_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.<Get>g__RentAsync|33_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
   at NBXplorer.Extensions.ReliableOpenConnectionAsync(NpgsqlDataSource ds, CancellationToken cancellationToken) in /root/NBXplorer/NBXplorer/Extensions.cs:line 60
   at NBXplorer.HostedServices.DatabaseSetupHostedService.StartAsync(CancellationToken cancellationToken) in /root/NBXplorer/NBXplorer/HostedServices/DatabaseSetupHostedService.cs:line 35
   at NBXplorer.HostedServices.DatabaseSetupHostedService.StartAsync(CancellationToken cancellationToken) in /root/NBXplorer/NBXplorer/HostedServices/DatabaseSetupHostedService.cs:line 36
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at NBXplorer.Program.Main(String[] args) in /root/NBXplorer/NBXplorer/Program.cs:line 55

`

**Comment by kosuodhmwa** [comment]
also not with other port:

`
root@debian12-btc-node:~/NBXplorer# dotnet run --no-launch-profile --no-build -c Release --project "NBXplorer/NBXplorer.csproj" --postgres "User ID=postgres;Host=postgres;Port=39382;Database=nbxplorer"
info: Configuration:  NBXplorer version 2.5.16
info: Configuration:  Data Directory: /root/.nbxplorer/Main
info: Configuration:  Configuration File: /root/.nbxplorer/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: NBXplorer.DatabaseSetup: Postgres services activated
Unhandled exception. System.Net.Sockets.SocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, Nullable`1 startingTimestamp)
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s, Int64 startingTimestamp)
   at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Npgsql.TaskTimeoutAndCancellation.ExecuteAsync(Func`2 getTaskFunc, NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.TaskTimeoutAndCancellation.ExecuteAsync[TResult](Func`2 getTaskFunc, NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
   at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|213_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.<Get>g__RentAsync|33_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
   at NBXplorer.Extensions.ReliableOpenConnectionAsync(NpgsqlDataSource ds, CancellationToken cancellationToken) in /root/NBXplorer/NBXplorer/Extensions.cs:line 60
   at NBXplorer.HostedServices.DatabaseSetupHostedService.StartAsync(CancellationToken cancellationToken) in /root/NBXplorer/NBXplorer/HostedServices/DatabaseSetupHostedService.cs:line 35
   at NBXplorer.HostedServices.DatabaseSetupHostedService.StartAsync(CancellationToken cancellationToken) in /root/NBXplorer/NBXplorer/HostedServices/DatabaseSetupHostedService.cs:line 36
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at NBXplorer.Program.Main(String[] args) in /root/NBXplorer/NBXplorer/Program.cs:line 55
`

**Comment by kosuodhmwa** [comment]
seems your docu is a lil but fu**ed up:

`
root@debian12-btc-node:~/NBXplorer# ./run.sh --chains=btc --network=regtest --postgres "Username=postgres;Host=127.0.0.1;Port=5432;Database=nbxplorer"
info: Configuration:  NBXplorer version 2.5.16
info: Configuration:  Data Directory: /root/.nbxplorer/RegTest
info: Configuration:  Configuration File: /root/.nbxplorer/RegTest/settings.config
info: Configuration:  Network: Regtest
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Regtest
info: Configuration:  Supported chains: BTC
info: NBXplorer.DatabaseSetup: Postgres services activated
Unhandled exception. Npgsql.NpgsqlException (0x80004005): No password has been provided but the backend requires one (in SASL/SCRAM-SHA-256-PLUS)

`

but now i also need to add pw...

**Comment by kosuodhmwa** [comment]
this: 

 ./run.sh --chains=btc --network=regtest --postgres "Username=postgres;password=MY_PG_PASS_HERE;Host=127.0.0.1;Port=5432;Database=nbxplorer"

**Comment by kosuodhmwa** [comment]
but cause tons of errors 
![image](https://github.com/user-attachments/assets/8b070c7a-b35e-4060-ab30-117cff6dcd85)

**Comment by kosuodhmwa** [comment]
ok, wrong network, so exception problem solved. but initial questions are still pendent

**Comment by kosuodhmwa** [comment]
(title changed)

**Comment by kosuodhmwa** [comment]
maybe the question is too complex?

**Comment by kosuodhmwa** [comment]
https://github.com/dgarage/NBXplorer/issues/500

**Comment by NicolasDorier** [comment]
If you plan installing BTCPay Server the best doc is https://docs.btcpayserver.org/Deployment/ManualDeploymentExtended
