### ISSUE TITLE
NBXplorerNetworkProvider Access Denied System.IO Exception C:\Users UWP

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#70]
The NBXplorerNetworkProvider constructor is somewhere trying to access C:\Users root, this is not allowed by UWP unless using a StreamReader or StreamWriter
var provider = new NBXplorerNetworkProvider((NetworkType)NetType);

System.IO Exception C:\Users Access Denied

If this class needs to do file operations can the path at least be configurable via the constructor?

Thanks

**Comment by NicolasDorier** [comment]
`sixjac` yes it is, `datadir` configuration.

**Comment by sixjac** [comment]
Hi Nicolas, thanks for the reply, I am using the Nuget C# package, can you point me to where datadir is?

Thanks

**Comment by NicolasDorier** [comment]
Ah sorry I misunderstood. Do you have any stack trace?

**Comment by sixjac** [comment]
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'NBXplorer.NBXplorerDefaultSettings' threw an exception.
  Source=NBXplorer.Client
  StackTrace:
   at NBXplorer.NBXplorerDefaultSettings.GetDefaultSettings(NetworkType networkType)
   at NBXplorer.NBXplorerNetwork..ctor(INetworkSet networkSet, NetworkType networkType)
   at NBXplorer.NBXplorerNetworkProvider.InitBitcoin(NetworkType networkType)
   at NBXplorer.NBXplorerNetworkProvider..ctor(NetworkType networkType)
   at BTCLib.BTCCore..ctor() in D:\InterkrankProjects\crypto-wallets\UWP\BitcoinWallet\btclib\BTCLib\BTCCore.cs:line 39
   at BTCLib.BTCCore.GetInstance() in D:\InterkrankProjects\crypto-wallets\UWP\BitcoinWallet\btclib\BTCLib\BTCCore.cs:line 32
   at BitcoinWallet.MainPage..ctor() in D:\InterkrankProjects\crypto-wallets\UWP\BitcoinWallet\BitcoinWallet\BitcoinWallet\MainPage.xaml.cs:line 41
   at BitcoinWallet.BitcoinWallet_XamlTypeInfo.XamlTypeInfoProvider.Activate_0_MainPage() in D:\InterkrankProjects\crypto-wallets\UWP\BitcoinWallet\BitcoinWallet\BitcoinWallet\obj\x64\Debug\XamlTypeInfo.g.cs:line 226
   at BitcoinWallet.BitcoinWallet_XamlTypeInfo.XamlUserType.ActivateInstance() in D:\InterkrankProjects\crypto-wallets\UWP\BitcoinWallet\BitcoinWallet\BitcoinWallet\obj\x64\Debug\XamlTypeInfo.g.cs:line 382

Inner Exception 1:
UnauthorizedAccessException: Access to the path 'C:\Users' is denied.

**Comment by NicolasDorier** [comment]
Looking to it, this should not ask you access to file...

**Comment by sixjac** [comment]
Ok but it looks like some system.io operation is being attempted somewhere and UWP does not allow access to C:\Users cause of the sandbox/security garbage. Cheers

**Comment by NicolasDorier** [comment]
Ok found, it is a bug. Fixing it now.

**Comment by sixjac** [comment]
Cool thanks

**Comment by NicolasDorier** [comment]
I just pushed `1.0.2.14` which should be available soon on nuget, can you update and close this issue if it fix your problem?

**Comment by sixjac** [comment]
Sure will, thanks Nicolas.

**Comment by sixjac** [comment]
Still waiting, not sure how long it normally takes for NuGet to publish.

**Comment by sixjac** [comment]
Did you update to NBXplorerx.Client?

**Comment by NicolasDorier** [comment]
I don't know, you should have it https://www.nuget.org/packages/NBXplorer.Client

**Comment by sixjac** [comment]
No there are 2 NBXplorer.Client and NBXplorerx.Client, I have NBXplorerx.Client because i thought the 'x' meant cross platform......

Thanks

**Comment by NicolasDorier** [comment]
mmmh, I have not created `NBXplorerx` be careful might be malware?

**Comment by NicolasDorier** [comment]
Ah no this is @Deimos wished they renamed better :/

**Comment by sixjac** [comment]
Ah ok thanks

**Comment by sixjac** [comment]
Wonderful, works, thanks a million!
