### ISSUE TITLE
Configure and Connect Issues

### ISSUE THREAD

**Issue by sixjac** [dgarage/NBXplorer#98]
How do I configure NBXplorer server on remote VPS so I can connect to it via external client

**Comment by NicolasDorier** [comment]
NBXplorer is not meant to be publicly exposed. If you need use `bind=0.0.0.0:PORT`

**Comment by NicolasDorier** [comment]
Read https://github.com/dgarage/NBXplorer/blob/master/docs/API.md and use NBXplorer.Client https://programmingblockchain.gitbooks.io/programmingblockchain/content/wallet/web-api.html

**Comment by sixjac** [comment]
I have read these, it still does not explain the basic step of where to tell NBXplorer.Client where and by what method to connect to NBXplorer server. I know how to use it by C# but basic connection steps are omitted

**Comment by NicolasDorier** [comment]
If you run this program on the same machine you run nbxplorer it will just work out of the box.

```
var network = new NBXplorerNetworkProvider(ChainType.Main).GetBTC();
var userExtKey = new ExtKey();
var userDerivationScheme = network.DerivationStrategyFactory.CreateDirectDerivationStrategy(userExtKey.Neuter(), new DerivationStrategyOptions()
{
    // Use non-segwit
    Legacy = true
});
ExplorerClient client = new ExplorerClient(network);
client.Track(userDerivationScheme);
```

`new ExplorerClient()` has other overload if you are running on a different address.

**Comment by sixjac** [comment]
Ah ok the optional server address well that makes sense ;)

**Comment by sixjac** [comment]
Call to: 
GetTransactionsResponse response = await NBXClient.GetTransactionsAsync(NBXTrackingStrategy, null, true);

caught exception, below stack trace:

   at System.Net.Http.HttpClientHandler.<SendAsync>d__111.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NBXplorer.ExplorerClient.<SendAsync>d__60`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BTCLib.BTCCore.<ReceiveTransactions>d__17.MoveNext()

I have btc nore running on vps server with NBXplorer running fine and set NBXplorer settings.conf bind=0.0.0.0 port=91

My remote client fails to connect to NBXplorer on remote hosted VPS server , I guess cause of username and password of server but ExplorerClient constructor only takes URI, should I bypass and just use HttpRequest object with Auth and raw JSON RPC calls?

**Comment by NicolasDorier** [comment]
you don't give the full stacktrace here. Also you need to remove authentication with --noauth

**Comment by sixjac** [comment]
Full stack trace for thrown exception from call: NBXClient.Track(NBXTrackingStrategy);

System.Net.Http.HttpRequestException
  HResult=0x800C000E
  Message=An error occurred while sending the request.
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.HttpClientHandler.<SendAsync>d__111.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NBXplorer.ExplorerClient.<SendAsync>d__60`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NBXplorer.ExplorerClient.Track(DerivationStrategyBase strategy, CancellationToken cancellation)
   at BTCLib.BTCCore.SetUserDerivationScheme() in D:\BitcoinWallet\BTCLib\BTCLib\BTCCore.cs:line 301
   at BitcoinWallet.MainPage.OnCredsButtonClick(Object sender, RoutedEventArgs e) in D:\BitcoinWallet\BitcoinWallet\BitcoinWallet\MainPage.xaml.cs:line 382

Inner Exception 1:
COMException: A security problem occurred. (Exception from HRESULT: 0x800C000E)

setting NoAuth=1 in conf file makes no difference, NBXplorer running fine on remote server just cannot connect to it via client

**Comment by NicolasDorier** [comment]
your error means the client don't manage to contact the client, probably firewall. Else I don't know :/

**Comment by sixjac** [comment]
Nicolas, do you some documentation or example on connecting to NBXplorer server on remote machine from NBXplorer client C# code?

Thanks

**Comment by sixjac** [comment]
Hi Nicolas, in regards to the above error it seems to be corelated to the following link:

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/eefa0d59-72a5-4b5a-9b12-5a11671f887f/uwpthrow-exception-a-security-problem-occurred-exception-from-hresult-0x800c000e-when-url?forum=wpdevelop 

So can the connection implementation please be changed to use HttpClient for connection to the running remote NBXplorer.dll/Server?

Thanks

**Comment by NicolasDorier** [comment]
Back from holiday. You managed to solve it?

**Comment by sixjac** [comment]
Hi Nicolas,

Yes, I was over thinking it, I started writing a server console app to do middle man communication but I soon figured out that everytime I closed my VPS session the running NBXplorer dll got terminated and therefore obviously it failed to connect from the client.
Installing screen on Linux solved it.

Regards,
Sean Ryan

________________________________
